### ISSUE TITLE
Opens 404 Error for Github

### ISSUE THREAD

**Issue by robbiegleeson** [robbiegleeson/repo#2]
Running command `repo` in a Github project opens `404 Page Not Found`.

Works okay for Gitlab

**Comment by gawhelan** [comment]
Steps to reproduce?

**Comment by robbiegleeson** [comment]
1. Navigate to Git repo root directory 
2. Run command 'repo' 
3. Observe. 

Expected: Opens browser on git project page or tree/branch 

Actual: Opens browser with 404 error. 

Git repo used for testing: https:www.gtihub.com/robbiegleeson/gistHub
